image: michaelmcandrew/civicrm-buildkit:php8.0

variables:
  CIVICRM_EXT_KEY:
    value: ""
    description: "The extension key (in long-form, if it uses the old style, ex: org.example.myext)"
  CIVICRM_EXT_TAG:
    value: ""
    description: "Release tag to process"

before_script:
  - apt -qq update && apt -qq install -y moreutils gettext
  - curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
  - source ~/.bashrc
  - git config --global user.email "info+gitlab@civicrm.org"
  - git config --global user.name "CiviCRM Gitlab CICD"

update_transifex_extension:
  stage: build
  cache:
    - key:
      paths:
        - civicrm-l10n-extensions/
  script:
    - php -v
    - tx --version
    - civistrings --version
    - git clone https://mlutfy-civicrm:${GITHUB_TOKEN}@github.com/civicrm/civicrm-l10n-extensions.git || true
    - cd civicrm-l10n-extensions
    - git checkout -- .
    - git pull origin master
    - php ../bin/civiextensions-update-transifex.php --extkey="${CIVICRM_EXT_KEY}" --exttag="${CIVICRM_EXT_TAG}"
    - git diff
  when: manual
  tags:
    - test-1-docker

commit_to_git:
  stage: deploy
  cache:
    - key:
      paths:
        - civicrm-l10n-extensions/
  script:
    - cd civicrm-l10n-extensions
    - git diff
    - git add po
    - git commit -m "Automatic commit (key=${CIVICRM_EXT_KEY:-all}, tag=${CIVICRM_EXT_TAG:-all})"
    - git push origin master
  when: manual
  tags:
    - test-1-docker
