image: michaelmcandrew/civicrm-buildkit:latest

variables:
  CIVICRM_EXT_KEY:
    value: ""
    description: "The extension key (in long-form, if it uses the old style, ex: org.example.myext)"
  CIVICRM_EXT_TAG:
    value: ""
    description: "Release tag to process"

before_script:
  - apt -qq update && apt -qq install -y moreutils gettext
  - curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
  - source ~/.bashrc

update_transifex_extension:
  stage: build
  script:
    - tx --version
    - php bin/civiextensions-update-transifex.php --extkey="${CIVICRM_EXT_KEY}" --exttag="${CIVICRM_EXT_TAG}"
  when: manual
  tags:
    - test-1-docker
